name: Revert Specific Files After Merge

on:
  pull_request:
    types:
      - closed  # This event is triggered when a pull request is closed (including when it is merged)
    branches:
      - main
      - Test-Area

jobs:
  revert_files:
    runs-on: ubuntu-latest

    steps:
    # Ensure the pull request was merged, not just closed
    - name: Check if the pull request was merged
      if: ${{ github.event.pull_request.merged == true }}
      run: echo "Pull request was merged, proceeding with the workflow."

    # Checkout the repository and ensure we fetch enough history to access the previous commit
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 5  # Fetch at least two commits (HEAD and HEAD^)

    # Get the files changed in the merge
    - name: Check for file changes
      id: file_changes
      run: |
        FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $FILES"
        if echo "$FILES" | grep -q 'inc/dbh.inc.php\|.cpanel.yml'; then
          echo "Changes detected in inc/dbh.inc.php or .cpanel.yml"
          echo "update_required=true" >> $GITHUB_ENV
        else
          echo "No changes detected in the specific files."
          echo "update_required=false" >> $GITHUB_ENV

    # Configure Git User for Commit
    - name: Configure Git User
      if: env.update_required == 'true'
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    # If changes were detected in the specific files, revert them
    - name: Revert specific files
      if: env.update_required == 'true'
      run: |
        git checkout HEAD^ -- inc/dbh.inc.php
        git checkout HEAD^ -- .cpanel.yml
        git commit -m "Revert changes to inc/dbh.inc.php and .cpanel.yml"

    # Push the changes back to the branch
    - name: Push changes
      if: env.update_required == 'true'
      run: |
        git push origin HEAD:${{ github.ref_name }}
